<?php

return [

    // frontend
    'guest'      => [
        'admin/index'       => '*',
        'index/index'       => '*',
        'index/set/'         => '*',
        'index/error'       => '*',
        'page/index'        => '*',
        'publication/index' => '*',
        'sitemap/index'     => '*',
        'forum/index'       => '*',
        'forum/index/search'       => '*',
        'post/index'       => '*',
        'post/index/search'       => '*',
        'post/index/comment'       => '*',
        'message/index'       => '*',
        'message/index/send'       => '*',
        'public/files' => '*',
        'printfile/index' => '*',
    ],
    'member'     => [
        'index/index' => '*',
    ],
    // backend
    'journalist' => [
        'publication/admin'  => [
            'index',
            'add',
            'edit',
        ],
        'page/admin'         => [
            'index',
            'add',
            'edit',
        ],
        'file-manager/index' => '*',
    ],
    'editor'     => [
        'publication/admin'  => '*',
        'publication/type'   => '*',
        'cms/translate'      => '*',
        'widget/admin'       => '*',
        'file-manager/index' => '*',
        'page/admin'         => '*',
        'tree/admin'         => '*',
        'seo/sitemap'        => '*',
    ],
    'admin'      => [
        'admin/admin-user'   => '*',
        'cms/configuration'  => '*',
        'cms/translate'      => '*',
        'cms/language'       => '*',
        'cms/javascript'     => '*',
        'widget/admin'       => '*',
        'file-manager/index' => '*',
        'page/admin'         => '*',
        'publication/admin'  => '*',
        'publication/type'   => '*',
        'seo/robots'         => '*',
        'seo/sitemap'        => '*',
        'seo/manager'        => '*',
        'tree/admin'         => '*',
        'clinic/index'       => '*',
        'clinic/form'        => '*',
        'clinic/review'      => '*',
        'clinic/news' => '*',
        'clinic/news/add' => '*',
        'clinic/news/edit' => '*',
        'clinic/news/delete' => '*',
        'clinic/news/check' => '*',
        'clinic/news/read' => '*',
        'clinic/forum' => '*',
        'clinic/post' => '*',
        'clinic/dataanaly' => '*',
        'clinic/dataanaly/index' => '*',
        'printfile/index' => '*',

    ],
    'clinic-center'      => [
        'admin/index'       => '*',
        'index/index'       => '*',
        'index/error'       => '*',
        'admin/index'   => '*',
        'clinic/index'   => '*',
        'clinic/form'   => '*',
        'clinic/review' => '*',
    ],
    'cc-user'      => [
        'publication/index' =>'*',
        'page/index'        => '*',
        'admin/index'       => '*',
        'index/index'       => '*',
        'index/error'       => '*',
        'admin/index'   => '*',
        'clinic/index'   => '*',
        'clinic/form'   => '*',
        'clinic/review' => '*',
        'clinic-admin/exportword'   => '*',
        'clinic/news' => '*',
        'clinic/news/check' => '*',
        'clinic/news/read' => '*',
        'forum/index'       => '*',
        'forum/index/search'       => '*',
        'post/index'       => '*',
        'post/index/search'       => '*',
        'post/index/comment'       => '*',
        'clinic/forum' => '*',
        'clinic/post' => '*',
        'public/files' => '*',
    ],
    'cc-approver'      => [
        'publication/index' =>'*',
        'page/index'        => '*',
        'admin/index'       => '*',
        'index/index'       => '*',
        'index/error'       => '*',
        'admin/index'   => '*',
        'clinic/index'   => '*',
        'clinic/form'   => '*',
        'clinic/review' => '*',
        'clinic-admin/exportword'   => '*',
        'clinic/news' => '*',
        'clinic/news/check' => '*',
        'clinic/news/read' => '*',
        'forum/index'       => '*',
        'forum/index/search'       => '*',
        'post/index'       => '*',
        'post/index/search'       => '*',
        'post/index/comment'       => '*',
        'clinic/forum' => '*',
        'clinic/post' => '*',
    ],
    'cc-admin'      => [
        'publication/index' =>'*',
        'page/index'        => '*',
        'admin/index'       => '*',
        'index/index'       => '*',
        'index/error'       => '*',
        'admin/index'   => '*',
        'admin/admin-user'   => '*',
        'clinic/index'   => '*',
        'clinic/form'   => '*',
        'clinic/review' => '*',
        'clinic-admin/admin-user'   => '*',
        'clinic-admin/amphur'   => '*',
        'clinic-admin/office'   => '*',
        'clinic-admin/session'   => '*',
        'clinic-admin/survey-status'   => '*',
        'clinic-admin/survey'   => '*',
        'clinic-admin/exportword'   => '*',
        'clinic-admin/news-type'   => '*',
        'clinic-admin/news-level'   => '*',
        'clinic-admin/news-important'   => '*',
        'clinic-admin/print-report'   => '*',
        'clinic-admin/condition'   => '*',
        'clinic/news' => '*',
        'clinic/news/add' => '*',
        'clinic/news/edit' => '*',
        'clinic/news/delete' => '*',
        'clinic/news/check' => '*',
        'clinic/news/read' => '*',
        'clinic/forum' => '*',
        'clinic/post' => '*',
        'clinic/dataanaly' => '*',
        'clinic/dataanaly/index' => '*',
        'clinic/message' => '*',
        'clinic/message/index' => '*',
        'clinic/message/search' => '*',
        'clinic/message/read' => '*',
        'printfile/index' => '*'
    ],
];
